services:
  be:
    container_name: orchidbe
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - "4040:8080"
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASS
    networks:
      - sba

networks:
  sba:
    driver: bridge