name: CI - Test with H2

on:
  workflow_dispatch:
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run tests with H2 profile
        run: mvn clean test -f ./server/pom.xml -Dspring.profiles.active=h2
